bert_model: 
  learning_rate: 2e-5
  model_name: "answerdotai/ModernBERT-base"
  epochs: 5
  optimizer: "adamw"
  n_classes: 1

data:
  batch_size: 4
  max_length: 1024
  tokenizer_name: "answerdotai/ModernBERT-base"